const os = require('os')
console.log("free memory", os.freemem())
console.log("total memory",os.totalmem())
console.log("version",os.version())
console.log("processor",os.cpus())
console.log("ram",os.ram())